import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "@/components/Sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-[#0f172a] bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-900/40 via-[#0f172a] to-[#0f172a] text-slate-200 selection:bg-indigo-500/30">
          <Sidebar />
          <div className="p-4 sm:ml-64">
            <main className="min-h-[calc(100vh-2rem)] rounded-3xl bg-white/5 border border-white/10 backdrop-blur-sm relative overflow-hidden shadow-2xl shadow-indigo-500/10">
              {/* Decorative background elements inside main container */}
              <div className="absolute top-0 left-0 w-full h-full overflow-hidden -z-10 pointer-events-none">
                <div className="absolute -top-[50%] -left-[20%] w-[70%] h-[70%] rounded-full bg-indigo-500/5 blur-3xl"></div>
                <div className="absolute top-[20%] -right-[20%] w-[60%] h-[60%] rounded-full bg-purple-500/5 blur-3xl"></div>
              </div>

              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
